### ISSUE TITLE
pointInteractionWithType:endedAtPoint: not called in Swift

### ISSUE THREAD

**Issue by Rhuantavan** [JohnSundell/SuperSpriteKit#5]
I have the following scene, which creates a label and a sprite. Both are subclassed, implement SSKInteractiveNode and define a pointInteractionWithType:endedAtPoint: function to be called on click. However pointInteractionWithType:endedAtPoint: is never called. Am I doing something wrong?

	import SpriteKit

	class GameScene: SKScene {
	    override func didMoveToView(view: SKView) {
       
	        let myLabel = LabelNode(fontNamed:"Chalkduster")
	        myLabel.text = "Hello, World!";
	        myLabel.fontSize = 65;
	        myLabel.position = CGPoint(x:CGRectGetMidX(self.frame), y:CGRectGetMidY(self.frame));
	        self.addChild(myLabel)
        
	        let sprite = SpriteNode(imageNamed:"Spaceship")
	        sprite.position = CGPoint(x:200, y:200)
	        sprite.setScale(0.5)
	        self.addChild(sprite)
	    }
    
	}

SKLabelNode subclass LabelNode

	class LabelNode: SKLabelNode, SSKInteractiveNode {

	    func pointInteractionWithType(type: SSKInteractionType, endedAtPoint point: CGPoint) {
	        println("test click")
	    }
    
	}

SKSpriteNode subclass SpriteNode

	class SpriteNode: SKSpriteNode, SSKInteractiveNode {
    
	    func pointInteractionWithType(type: SSKInteractionType, endedAtPoint point: CGPoint) {
	        println("test click")
	    }
    
	}

**Comment by JohnSundell** [comment]
@Rhuantavan You don't have an interaction handler. Create a `SSKInteractionHandler` instance and add it to your `SKView`.

**Comment by Rhuantavan** [comment]
I did add the SSKInteractionHandler. Here's my application delegate:

	import Cocoa
	import SpriteKit

	@NSApplicationMain
	class AppDelegate: NSObject, NSApplicationDelegate {
		
		@IBOutlet weak var window: NSWindow!
		@IBOutlet weak var skView: SKView!
		var intHandler: SSKInteractionHandler
		
		override init() {
			intHandler = SSKInteractionHandler()
		}
		
		func applicationDidFinishLaunching(aNotification: NSNotification) {
			// Register some custom fonts
			registerFontWithFileName("CrimsonText-Bold.ttf")
			registerFontWithFileName("CrimsonText-BoldItalic.ttf")
			registerFontWithFileName("CrimsonText-Italic.ttf")
			registerFontWithFileName("CrimsonText-Roman.ttf")
			
			skView.showsFPS = true
			skView.showsNodeCount = true
			skView.showsDrawCount = true
			
			skView.ssk_addInteractionHandler(intHandler)
			// Fix for keyboard events not firing until mouse is clicked inside the view
			if let viewResponder = skView.subviews[0] as? NSResponder {
				self.window.makeFirstResponder(viewResponder)
			}
			
			self.window.acceptsMouseMovedEvents = true
			
			// Load and show the initial scene
			skView.presentScene(GameEntryScene())
		}
		
		func applicationShouldTerminate(sender: NSApplication) -> NSApplicationTerminateReply {
			GameManager.sharedManager.gameWillQuit()
			return .TerminateNow
		}
		
		func applicationShouldTerminateAfterLastWindowClosed(sender: NSApplication) -> Bool {
			GameManager.sharedManager.gameWillQuit()
			return true
		}
		
		func registerFontWithFileName(fontName: String) {
			let fontFileFull = NSBundle.mainBundle().resourcePath! + "/" + fontName
			let fontURL = NSURL(fileURLWithPath: fontFileFull)
			CTFontManagerRegisterFontsForURL(fontURL, .Process, nil)
		}

	}
